### ISSUE TITLE
Update screen partials $maxResults attribute in Form

### ISSUE THREAD

**Issue by martinberlin** [martinberlin/cale-integrations#73]
This request was made by @UsefulElectronics that collaborated in the ESP-IDF component adding some new corrections and a DKE display.

The idea is just to accept a length up to 19 elements maxResults so it's possible to show weather rows for a longer timeframe
Related to #45 

![openweather](https://pbs.twimg.com/media/F1Ay5a2XsA0iqa8?format=png&name=900x900)

**Comment by UsefulElectronics** [comment]
Great ! 
I will test it and post the result

**Comment by martinberlin** [comment]
![Screen preview](https://github.com/martinberlin/cale-integrations/assets/2692928/250393ab-f96d-4bfb-bfb5-3f7cfc71b714)

As an admin I can preview other's screens. Yours looks nicer now!

**Comment by UsefulElectronics** [comment]
![image](https://github.com/martinberlin/cale-integrations/assets/72943786/73c0041d-1aeb-480c-b56e-6aa8bff74710)

**Comment by UsefulElectronics** [comment]
Tested and look stunning!

**Comment by martinberlin** [comment]
Thanks, merged and deployed
